# Generated by Django 2.1.4 on 2019-03-12 14:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Each_discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commented', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(default='')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Developer')),
            ],
        ),
    ]
