# Generated by Django 2.1.5 on 2019-03-05 16:54

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0011_auto_20190305_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
